/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Makefile                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: antabord <antabord@student.42.fr>          #+#  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025-04-16 10:03:49 by antabord          #+#    #+#             */
/*   Updated: 2025-04-16 10:03:49 by antabord         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

SRC	=	ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_memcpy.c 
	ft_memmove.c ft_memset.c ft_strlcpy.c ft_strlcat.c ft_strlen.c

OBJ =	$(SRC: .c=.o)

BONUS